apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-delegate
  namespace: harness-delegate-ng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harness-delegate
  template:
    metadata:
      labels:
        app: harness-delegate
    spec:
      containers:
      - name: harness-delegate
        image: harness/delegate:latest
        env:
        - name: ACCOUNT_ID
          value: "<your-harness-account-id>"
        - name: DELEGATE_TOKEN
          value: "<your-delegate-token>"
        - name: MANAGER_HOST_AND_PORT
          value: "https://app.harness.io/gratis"
        - name: DELEGATE_NAME
          value: "aks-delegate"
        - name: DELEGATE_TYPE
          value: "KUBERNETES"
        - name: NEXT_GEN
          value: "true"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: harness-delegate
  namespace: harness-delegate-ng
spec:
  type: ClusterIP
  selector:
    app: harness-delegate
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
