apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-delegate
  namespace: harness-delegate-ng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harness-delegate
  template:
    metadata:
      labels:
        app: harness-delegate
    spec:
      containers:
      - name: harness-delegate
        image: harness/delegate:latest
        env:
        - name: DELEGATE_NAME
          value: gke-delegate
        - name: ACCOUNT_ID
          value: <YOUR_HARNESS_ACCOUNT_ID>
        - name: MANAGER_HOST_AND_PORT
          value: https://app.harness.io/gratis
        - name: DELEGATE_TOKEN
          value: <YOUR_DELEGATE_TOKEN>
